# Generated by Django 3.0.4 on 2020-05-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facesite',
            new_name='Facedb',
        ),
    ]
