# Generated by Django 3.0.4 on 2020-05-06 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_auto_20200502_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedb',
            name='click',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
